CREATE PROCEDURE DW.DimPersonStaging_Create
AS
BEGIN
	
	SET NOCOUNT ON;
	
	BEGIN TRY

		BEGIN TRANSACTION;

			DROP TABLE IF EXISTS DW.DimPersonStaging;

			CREATE TABLE DW.DimPersonStaging(				
				PersonnelCode VARCHAR(8) NOT NULL,
				FirstName VARCHAR(50) NOT NULL,
				LastName VARCHAR(50) NOT NULL,
				PlayerDebutDate DATE NULL,
				ManagerDebutDate DATE NULL,
				CoachDebutDate DATE NULL,
				UmpireDebutDate DATE NULL
			) ON [PRIMARY];

		COMMIT TRANSACTION;

	END TRY

	BEGIN CATCH

		ROLLBACK TRANSACTION;

	END CATCH

END