CREATE PROCEDURE DW.DimTeamStaging_Create
AS
BEGIN
	
	SET NOCOUNT ON;
	
	BEGIN TRY

		BEGIN TRANSACTION;

			DROP TABLE IF EXISTS DW.DimTeamStaging;

			CREATE TABLE DW.DimTeamStaging (
				CurrentFranchiseCode VARCHAR(3) NOT NULL,
				ActualFranchiseCode VARCHAR(3) NOT NULL,
				League VARCHAR(2) NOT NULL,
				Division VARCHAR(1) NOT NULL,
				[Location] VARCHAR(30) NOT NULL,
				Nickname VARCHAR(30) NOT NULL,
				AlternateNicknames VARCHAR(30) NOT NULL,
				FirstGameDate DATE NOT NULL,
				LastGameDate DATE NULL,
				City VARCHAR(30) NOT NULL,
				[State] VARCHAR(2) NOT NULL
			);

		COMMIT TRANSACTION;

	END TRY

	BEGIN CATCH

		ROLLBACK TRANSACTION;

	END CATCH

END