CREATE TABLE DW.FactGameSummary
(
	GameSummaryId								INT IDENTITY(1, 1) NOT NULL,
	BallParkId									INT NOT NULL,
	DateId										INT NOT NULL,
	GameNumberOnDateId							INT NOT NULL,
	VisitingTeamId								INT NOT NULL,
	--VisitingTeamLeagueId						INT NOT NULL,
    VisitingTeamGameNumber						SMALLINT NOT NULL,
    HomeTeamId									INT NOT NULL,
    --HomeTeamLeagueId							INT NOT NULL,
    HomeTeamGameNumber							SMALLINT NOT NULL,
    VisitingTeamScore							SMALLINT NOT NULL,
    HomeTeamScore								SMALLINT NOT NULL,
    GameLengthInOuts							SMALLINT NOT NULL,
    GameDayOrNight                              VARCHAR (50)  NULL,
    CompletionInformation                       VARCHAR (50)  NULL,
    ForfeitInformation                          VARCHAR (50)  NULL,
    ProtestInformation                          VARCHAR (50)  NULL,
    GameAttendance								INT NOT NULL,
    GameTimeInMinutes							INT NOT NULL,
    VisitingTeamLineScore                       VARCHAR (50)  NULL,
    HomeTeamLineScore                           VARCHAR (50)  NULL,
    VisitingTeamAtBats                          SMALLINT  NULL,
    VisitingTeamHits                            SMALLINT  NULL,
    VisitingTeamDoubles                         SMALLINT  NULL,
    VisitingTeamTriples                         SMALLINT  NULL,
    VisitingTeamHomeRuns                        SMALLINT  NULL,
    VisitingTeamRBI                             SMALLINT  NULL,
    VisitingTeamSacrificeHits                   SMALLINT  NULL,
    VisitingTeamSacrificeFlies                  SMALLINT  NULL,
    VisitingTeamHitByPitch                      SMALLINT  NULL,
    VisitingTeamWalks                           SMALLINT  NULL,
    VisitingTeamIntentionalWalks                SMALLINT  NULL,
    VisitingTeamStrikeouts                      SMALLINT  NULL,
    VisitingTeamStolenBases                     SMALLINT  NULL,
    VisitingTeamCaughtStealing                  SMALLINT  NULL,
    VisitingTeamGroundedIntoDoublePlays         SMALLINT  NULL,
    VisitingTeamAwardedFirstCatcherInterference SMALLINT  NULL,
    VisitingTeamLeftOnBase                      SMALLINT  NULL,
    VisitingTeamPitchersUsed                    SMALLINT  NULL,
    VisitingTeamIndividualEarnedRuns            SMALLINT  NULL,
    VisitingTeamTeamEarnedRuns                  SMALLINT  NULL,
    VisitingTeamWildPitches                     SMALLINT  NULL,
    VisitingTeamBalks                           SMALLINT  NULL,
    VisitingTeamPutOuts                         SMALLINT  NULL,
    VisitingTeamAssists                         SMALLINT  NULL,
    VisitingTeamErrors                          SMALLINT  NULL,
    VisitingTeamPassedBalls                     SMALLINT  NULL,
    VisitingTeamDoublePlays                     SMALLINT  NULL,
    VisitingTeamTriplePlays                     SMALLINT  NULL,
    HomeTeamAtBats                              SMALLINT  NULL,
    HomeTeamHits                                SMALLINT  NULL,
    HomeTeamDoubles                             SMALLINT  NULL,
    HomeTeamTriples                             SMALLINT  NULL,
    HomeTeamHomeRuns                            SMALLINT  NULL,
    HomeTeamRBI                                 SMALLINT  NULL,
    HomeTeamSacrificeHits                       SMALLINT  NULL,
    HomeTeamSacrificeFlies                      SMALLINT  NULL,
    HomeTeamHitByPitch                          SMALLINT  NULL,
    HomeTeamWalks                               SMALLINT  NULL,
    HomeTeamIntentionalWalks                    SMALLINT  NULL,
    HomeTeamStrikeouts                          SMALLINT  NULL,
    HomeTeamStolenBases                         SMALLINT  NULL,
    HomeTeamCaughtStealing                      SMALLINT  NULL,
    HomeTeamGroundedIntoDoublePlays             SMALLINT  NULL,
    HomeTeamAwardedFirstCatcherInterference     SMALLINT  NULL,
    HomeTeamLeftOnBase                          SMALLINT  NULL,
    HomeTeamPitchersUsed                        SMALLINT  NULL,
    HomeTeamIndividualEarnedRuns                SMALLINT  NULL,
    HomeTeamTeamEarnedRuns                      SMALLINT  NULL,
    HomeTeamWildPitches                         SMALLINT  NULL,
    HomeTeamBalks                               SMALLINT  NULL,
    HomeTeamPutOuts                             SMALLINT  NULL,
    HomeTeamAssists                             SMALLINT  NULL,
    HomeTeamErrors                              SMALLINT  NULL,
    HomeTeamPassedBalls                         SMALLINT  NULL,
    HomeTeamDoublePlays                         SMALLINT  NULL,
    HomeTeamTriplePlays                         SMALLINT  NULL,
	CONSTRAINT PK_FactGameSummary PRIMARY KEY CLUSTERED (GameSummaryId)
)
